use crate::code_builder::CodeBuilder;
pub use crate::spec::{EnumSpec, FieldSpec, MessageDefinition, StructSpec};
use log::{debug, info};

pub fn assign_message_numbers(
    spec: &mut MessageDefinition,
    prefix: &str,
    start_number: u32,
    num_digits: u8,
    enable_prefix: bool,
) -> u32 {
    // Return highest assigned number
    // First scan: Find all explicitly assigned numbers and the highest one
    let mut highest_explicit_number = 0;
    let mut used_numbers = std::collections::HashSet::new();

    for category in &spec.messages {
        for message in &category.messages {
            if let Some(number) = message.number {
                highest_explicit_number = highest_explicit_number.max(number);

                // Track used numbers to avoid duplicates
                if !used_numbers.insert(number) {
                    log::warn!(
                        "Duplicate message number {} found for {}",
                        number,
                        message.original_name
                    );
                }
            }
        }
    }

    info!("Highest explicit message number: {highest_explicit_number}");
    debug!("Used message numbers: {used_numbers:?}");

    // Start with max(start_number, highest_explicit_number + 1)
    let mut current_number = start_number.max(highest_explicit_number + 1);
    let mut highest_assigned_number = highest_explicit_number;

    // Second scan: Assign numbers to messages without explicit numbering
    for category in &mut spec.messages {
        for message in &mut category.messages {
            // Get or assign message number
            let message_number = if let Some(number) = message.number {
                number // Use explicit number
            } else {
                // Find next available number (skip any that are already used)
                while used_numbers.contains(&current_number) {
                    current_number += 1;
                }

                let number = current_number;
                message.number = Some(number); // Store the assigned number
                used_numbers.insert(number);
                current_number += 1;
                number
            };

            highest_assigned_number = highest_assigned_number.max(message_number);

            // Generate message name based on number
            if enable_prefix {
                let number_str = format!("{:0width$}", message_number, width = num_digits as usize);
                message.generated_name =
                    format!("{}{}_{}", prefix, number_str, message.original_name);
            } else {
                message.generated_name = message.original_name.clone();
            }

            debug!(
                "Message: {} -> Number: {}, Name: {}",
                message.original_name, message_number, message.generated_name
            );
        }
    }

    highest_assigned_number
}

pub fn generate_file_header(spec: &MessageDefinition) -> String {
    let mut builder = CodeBuilder::new();

    // Get current time
    let now = chrono::Local::now();
    let timestamp = now.format("%Y-%m-%d %H:%M:%S").to_string();

    // File header
    builder
        .add_raw_line(&format!(
            "// This file was automatically generated on {timestamp}. DO NOT EDIT MANUALLY!"
        ))
        .add_raw_line("// Generated by genrmsg - RUST Message Generator")
        .add_raw_line("");

    // Module documentation
    builder
        .add_raw_line(&format!("//! {}", spec.settings.module_doc))
        .add_raw_line("");

    // Allow camel case for message names
    builder
        .add_raw_line("#![allow(non_camel_case_types)]")
        .add_raw_line("");

    // Standard imports
    builder
        .add_raw_line("use chrono::{DateTime, NaiveDate, Utc};")
        .add_raw_line("use serde::{Deserialize, Serialize};")
        .add_raw_line("use std::fmt::{self, Display};")
        .add_raw_line("use std::str::FromStr;")
        .add_raw_line("");

    builder.build()
}

pub fn generate_enum_code(enum_name: &str, enum_spec: &EnumSpec) -> String {
    let mut builder = CodeBuilder::new();

    builder.add_doc_comment(&enum_spec.description);
    builder.add_attribute("derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)");

    // Generate enum with variants
    builder.block(&format!("pub enum {enum_name} {{"), "}", |builder| {
        for variant in &enum_spec.variants {
            builder.add_line(&format!("{variant},"));
        }
    });

    builder.add_raw_line("");

    // Implement Display trait if requested
    if enum_spec.implement_traits.contains(&"Display".to_string()) {
        builder.block(
            &format!("impl Display for {enum_name} {{"),
            "}",
            |builder| {
                builder.block(
                    "fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {",
                    "}",
                    |builder| {
                        builder.block("match self {", "}", |builder| {
                            for variant in &enum_spec.variants {
                                builder.add_line(&format!(
                                    "{}::{} => write!(f, \"{}\"),",
                                    enum_name,
                                    variant,
                                    variant.to_lowercase()
                                ));
                            }
                        });
                    },
                );
            },
        );

        builder.add_raw_line("");
    }

    if enum_spec.implement_traits.contains(&"FromStr".to_string()) {
        builder.add_line(&format!("impl FromStr for {enum_name} {{"));
        builder.indent();
        builder.add_line("type Err = &'static str;");
        builder.add_raw_line("");
        builder.block(
            "fn from_str(s: &str) -> Result<Self, Self::Err> {",
            "}",
            |builder| {
                builder.block("match s {", "}", |builder| {
                    for variant in &enum_spec.variants {
                        builder.add_line(&format!(
                            "\"{}\" => Ok({}::{}),",
                            variant.to_lowercase(),
                            enum_name,
                            variant
                        ));
                    }
                    builder.add_line("_ => Err(\"Invalid format\"),");
                });
            },
        );
        builder.dedent();
        builder.add_line("}");
        builder.add_raw_line("");
    }

    builder.build()
}

pub fn generate_all_enums(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    if let Some(enums) = &spec.enums {
        for (enum_name, enum_spec) in enums {
            code.push_str(&generate_enum_code(enum_name, enum_spec));
        }
    } else {
        code.push_str("// No enum structs defined\n");
    }

    code
}

pub fn generate_struct_code(struct_name: &str, struct_spec: &StructSpec) -> String {
    let mut builder = CodeBuilder::new();

    builder.add_doc_comment(&struct_spec.description);
    builder.add_attribute("derive(Debug, Clone, Serialize, Deserialize)");

    // Use the block method to create struct body with proper indentation
    builder.block(&format!("pub struct {struct_name} {{"), "}", |builder| {
        for (field_name, field) in &struct_spec.fields {
            builder.add_doc_comment(&field.description);
            builder.add_line(&format!("pub {}: {},", field_name, field.type_name));
        }
    });

    builder.add_raw_line("");
    builder.build()
}

pub fn generate_common_structs(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    if let Some(common_structs) = &spec.common_structs {
        for (struct_name, struct_spec) in common_structs {
            code.push_str(&generate_struct_code(struct_name, struct_spec));
        }
    } else {
        code.push_str("// No common structs defined\n");
    }

    code
}

pub fn generate_error_message(spec: &MessageDefinition) -> String {
    let mut builder = CodeBuilder::new();

    // Generate error message
    builder.add_line("/// Error message for all possible errors");
    builder.add_attribute("derive(Debug, Clone, Serialize, Deserialize)");

    if let Some(error_message) = &spec.error_message {
        builder.block("pub struct M900_Error {", "}", |builder| {
            for (field_name, field) in &error_message.fields {
                builder.add_doc_comment(&field.description);
                builder.add_line(&format!("pub {}: {},", field_name, field.type_name));
            }
        });

        builder.add_raw_line("");

        // Implement Display for error message
        builder.block("impl Display for M900_Error {", "}", |builder| {
            builder.block(
                "fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {",
                "}",
                |builder| {
                    builder
                        .add_line("write!(f, \"Error {}: {}\", self.error_id, self.error_message)");
                },
            );
        });

        builder.add_raw_line("");
    }

    builder.build()
}

pub fn generate_message_structs(spec: &MessageDefinition) -> (String, Vec<(String, String)>) {
    let mut builder = CodeBuilder::new();
    let mut message_enum_variants = Vec::new();

    for category in &spec.messages {
        builder.add_line(&format!("// {} messages", category.category));

        for message in &category.messages {
            let request_name = &message.generated_name;
            let response_name = format!("{request_name}_Reply");

            // Request struct
            builder.add_line(&format!("/// {} - Request", message.description));
            builder.add_line("#[derive(Debug, Clone, Serialize, Deserialize)]");
            builder.add_line(&format!("pub struct {request_name} {{"));

            builder.indent();

            let mut keys = message.request.fields.keys().collect::<Vec<_>>();
            keys.sort();
            for field_name in keys {
                let field = message.request.fields.get(field_name).unwrap();
                builder.add_doc_comment(&field.description);
                builder.add_line(&format!("pub {}: {},", field_name, field.type_name));
            }

            builder.dedent();

            builder.add_line("}");
            builder.add_raw_line("");

            // Response struct
            builder.add_line(&format!("/// {} - Response", message.description));
            builder.add_line("#[derive(Debug, Clone, Serialize, Deserialize)]");
            builder.add_line(&format!("pub struct {response_name} {{"));

            builder.indent();

            let mut keys = message.response.fields.keys().collect::<Vec<_>>();
            keys.sort();
            for field_name in keys {
                let field = message.response.fields.get(field_name).unwrap();
                builder.add_doc_comment(&field.description);
                builder.add_line(&format!("pub {}: {},", field_name, field.type_name));
            }

            builder.dedent();

            builder.add_line("}");
            builder.add_raw_line("");

            // Add to enum variants
            message_enum_variants.push((request_name.clone(), response_name));
        }

        builder.add_raw_line("");
    }

    (builder.build(), message_enum_variants)
}

pub fn generate_message_enum(message_enum_variants: &[(String, String)]) -> String {
    let mut builder = CodeBuilder::new();

    // Generate Message enum
    builder.add_line("/// A wrapper enum for all message types");
    builder.add_attribute("derive(Debug, Clone, Serialize, Deserialize)");
    builder.block("pub enum Message {", "}", |builder| {

        // Sort all messages according to their generated name
        let mut sorted_variants = message_enum_variants.to_vec();
        sorted_variants.sort_by(|a, b| a.0.cmp(&b.0));
        let message_enum_variants = sorted_variants;

        // Message variants
        for (request, response) in message_enum_variants {
            builder.add_line(&format!("{request}({request}),"));
            builder.add_line(&format!("{response}({response}),"));
        }

        // Add error message
        builder.add_line("M900_Error(M900_Error),");
    });
    builder.add_raw_line("");

    // Implement Display for Message enum
    builder.block("impl Display for Message {", "}", |builder| {
        builder.block(
            "fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {",
            "}",
            |builder| {
                builder.block("match self {", "}", |builder| {
                    for (request, response) in message_enum_variants {
                        builder.add_line(&format!(
                            "Message::{request}(_) => write!(f, \"{request}\"),"
                        ));
                        builder.add_line(&format!(
                            "Message::{response}(_) => write!(f, \"{response}\"),"
                        ));
                    }
                    builder.add_line("Message::M900_Error(_) => write!(f, \"M900_Error\"),");
                });
            },
        );
    });
    builder.add_raw_line("");

    builder.build()
}

pub fn generate_helper_functions() -> String {
    let mut builder = CodeBuilder::new();

    // Helper functions for serialization
    builder.add_line("// Helper functions for message serialization and deserialization");
    builder.block(
        "pub fn serialize_message(msg: &Message) -> Result<Vec<u8>, bincode::Error> {",
        "}",
        |builder| {
            builder.add_line("bincode::serialize(msg)");
        },
    );
    builder.add_raw_line("");

    builder.block(
        "pub fn deserialize_message(bytes: &[u8]) -> Result<Message, bincode::Error> {",
        "}",
        |builder| {
            builder.add_line("bincode::deserialize(bytes)");
        },
    );

    builder.build()
}

pub fn generate_rust_code(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    // Generate file header with module docs and imports
    code.push_str(&generate_file_header(spec));

    // Generate all enum types
    code.push_str(&generate_all_enums(spec));

    // Generate common structs
    code.push_str(&generate_common_structs(spec));

    // Generate error message
    code.push_str(&generate_error_message(spec));

    // Generate message structs
    let (message_structs, message_enum_variants) = generate_message_structs(spec);
    code.push_str(&message_structs);

    // Generate message enum
    code.push_str(&generate_message_enum(&message_enum_variants));

    // Generate helper functions
    code.push_str(&generate_helper_functions());

    code
}
