pub use crate::spec::{EnumSpec, FieldSpec, MessageDefinition, StructSpec};
use log::debug;

pub fn assign_message_numbers(
    spec: &mut MessageDefinition,
    prefix: &str,
    start_number: u32,
    num_digits: u8,
    enable_prefix: bool,
) {
    let mut current_number = start_number;

    for category in &mut spec.messages {
        for message in &mut category.messages {
            if enable_prefix {
                // Format the number with leading zeros according to num_digits
                let number_str = match num_digits {
                    1 => format!("{current_number}"),
                    2 => format!("{current_number:02}"),
                    3 => format!("{current_number:03}"),
                    4 => format!("{current_number:04}"),
                    5 => format!("{current_number:05}"),
                    6 => format!("{current_number:06}"),
                    _ => format!("{:0width$}", current_number, width = num_digits as usize),
                };

                // Create the new message name: PREFIX + NUMBER + _ + ORIGINAL_NAME
                message.generated_name =
                    format!("{}{}_{}", prefix, number_str, message.original_name);
            } else {
                // Just use the original name without prefixing
                message.generated_name = message.original_name.clone();
            }

            debug!("Assigning message name: {}", message.generated_name);
            current_number += 1;
        }
    }
}

pub fn generate_file_header(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    // File header
    code.push_str("// This file was automatically generated. DO NOT EDIT MANUALLY!\n");
    code.push_str("// Generated by genrmsg - MC Project Effort Message Generator\n\n");

    // Module documentation
    code.push_str(&format!("//! {}\n\n", spec.settings.module_doc));

    // Allow camel case for message names
    code.push_str("#![allow(non_camel_case_types)]\n\n");

    // Standard imports
    code.push_str("use chrono::{DateTime, NaiveDate, Utc};\n");
    code.push_str("use serde::{Deserialize, Serialize};\n");
    code.push_str("use std::fmt::{self, Display};\n");
    code.push_str("use std::str::FromStr;\n\n");

    code
}

pub fn generate_enum_code(enum_name: &str, enum_spec: &EnumSpec) -> String {
    let mut code = String::new();

    code.push_str(&format!("/// {}\n", enum_spec.description));
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n");
    code.push_str(&format!("pub enum {enum_name} {{\n"));

    for variant in &enum_spec.variants {
        code.push_str(&format!("    {variant},\n"));
    }

    code.push_str("}\n\n");

    // Implement traits
    if enum_spec.implement_traits.contains(&"Display".to_string()) {
        code.push_str(&format!("impl Display for {enum_name} {{\n"));
        code.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
        code.push_str("        match self {\n");

        for variant in &enum_spec.variants {
            code.push_str(&format!(
                "            {}::{} => write!(f, \"{}\"),\n",
                enum_name,
                variant,
                variant.to_lowercase()
            ));
        }

        code.push_str("        }\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");
    }

    if enum_spec.implement_traits.contains(&"FromStr".to_string()) {
        code.push_str(&format!("impl FromStr for {enum_name} {{\n"));
        code.push_str("    type Err = &'static str;\n\n");
        code.push_str("    fn from_str(s: &str) -> Result<Self, Self::Err> {\n");
        code.push_str("        match s {\n");

        for variant in &enum_spec.variants {
            code.push_str(&format!(
                "            \"{}\" => Ok({}::{}),\n",
                variant.to_lowercase(),
                enum_name,
                variant
            ));
        }

        code.push_str("            _ => Err(\"Invalid format\"),\n");
        code.push_str("        }\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");
    }

    code
}

pub fn generate_all_enums(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    for (enum_name, enum_spec) in &spec.enums {
        code.push_str(&generate_enum_code(enum_name, enum_spec));
    }

    code
}

pub fn generate_struct_code(struct_name: &str, struct_spec: &StructSpec) -> String {
    let mut code = String::new();

    code.push_str(&format!("/// {}\n", struct_spec.description));
    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str(&format!("pub struct {struct_name} {{\n"));

    for (field_name, field) in &struct_spec.fields {
        code.push_str(&format!("    /// {}\n", field.description));
        code.push_str(&format!("    pub {}: {},\n", field_name, field.type_name));
    }

    code.push_str("}\n\n");

    code
}

pub fn generate_common_structs(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    for (struct_name, struct_spec) in &spec.common_structs {
        code.push_str(&generate_struct_code(struct_name, struct_spec));
    }

    code
}

pub fn generate_error_message(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    // Generate error message
    code.push_str("/// Error message for all possible errors\n");
    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str("pub struct M900_Error {\n");

    for (field_name, field) in &spec.error_message.fields {
        code.push_str(&format!("    /// {}\n", field.description));
        code.push_str(&format!("    pub {}: {},\n", field_name, field.type_name));
    }

    code.push_str("}\n\n");

    // Implement Display for error message
    code.push_str("impl Display for M900_Error {\n");
    code.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    code.push_str("        write!(f, \"Error {}: {}\", self.error_id, self.error_message)\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code
}

pub fn generate_message_structs(spec: &MessageDefinition) -> (String, Vec<(String, String)>) {
    let mut code = String::new();
    let mut message_enum_variants = Vec::new();

    for category in &spec.messages {
        code.push_str(&format!("// {} messages\n", category.category));

        for message in &category.messages {
            let request_name = &message.generated_name;
            let response_name = format!("{request_name}_Reply");

            // Request struct
            code.push_str(&format!("/// {} - Request\n", message.description));
            code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
            code.push_str(&format!("pub struct {request_name} {{\n"));

            for (field_name, field) in &message.request.fields {
                code.push_str(&format!("    /// {}\n", field.description));
                code.push_str(&format!("    pub {}: {},\n", field_name, field.type_name));
            }

            code.push_str("}\n\n");

            // Response struct
            code.push_str(&format!("/// {} - Response\n", message.description));
            code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
            code.push_str(&format!("pub struct {response_name} {{\n"));

            for (field_name, field) in &message.response.fields {
                code.push_str(&format!("    /// {}\n", field.description));
                code.push_str(&format!("    pub {}: {},\n", field_name, field.type_name));
            }

            code.push_str("}\n\n");

            // Add to enum variants
            message_enum_variants.push((request_name.clone(), response_name));
        }

        code.push('\n');
    }

    (code, message_enum_variants)
}

pub fn generate_message_enum(message_enum_variants: &[(String, String)]) -> String {
    let mut code = String::new();

    // Generate Message enum
    code.push_str("/// A wrapper enum for all message types\n");
    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str("pub enum Message {\n");

    // Message variants
    for (request, response) in message_enum_variants {
        code.push_str(&format!("    {request}({request}),\n"));
        code.push_str(&format!("    {response}({response}),\n"));
    }

    // Add error message
    code.push_str("    M900_Error(M900_Error),\n");
    code.push_str("}\n\n");

    // Implement Display for Message enum
    code.push_str("impl Display for Message {\n");
    code.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    code.push_str("        match self {\n");

    for (request, response) in message_enum_variants {
        code.push_str(&format!(
            "            Message::{request}(_) => write!(f, \"{request}\"),\n"
        ));
        code.push_str(&format!(
            "            Message::{response}(_) => write!(f, \"{response}\"),\n"
        ));
    }

    code.push_str("            Message::M900_Error(_) => write!(f, \"M900_Error\"),\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code
}

pub fn generate_helper_functions() -> String {
    let mut code = String::new();

    // Helper functions for serialization
    code.push_str("// Helper functions for message serialization and deserialization\n");
    code.push_str("pub fn serialize_message(msg: &Message) -> Result<Vec<u8>, bincode::Error> {\n");
    code.push_str("    bincode::serialize(msg)\n");
    code.push_str("}\n\n");

    code.push_str(
        "pub fn deserialize_message(bytes: &[u8]) -> Result<Message, bincode::Error> {\n",
    );
    code.push_str("    bincode::deserialize(bytes)\n");
    code.push_str("}\n");

    code
}

pub fn generate_rust_code(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    // Generate file header with module docs and imports
    code.push_str(&generate_file_header(spec));

    // Generate all enum types
    code.push_str(&generate_all_enums(spec));

    // Generate common structs
    code.push_str(&generate_common_structs(spec));

    // Generate error message
    code.push_str(&generate_error_message(spec));

    // Generate message structs
    let (message_structs, message_enum_variants) = generate_message_structs(spec);
    code.push_str(&message_structs);

    // Generate message enum
    code.push_str(&generate_message_enum(&message_enum_variants));

    // Generate helper functions
    code.push_str(&generate_helper_functions());

    code
}
