use clap::Parser;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use log::{error, info, debug};

#[derive(Debug, Serialize, Deserialize)]
struct Settings {
    output_file: String,
    module_doc: String,
    serialization_framework: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct FieldSpec {
    #[serde(rename = "type")]
    type_name: String,
    description: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct StructSpec {
    description: String,
    fields: HashMap<String, FieldSpec>,
}

#[derive(Debug, Serialize, Deserialize)]
struct EnumSpec {
    description: String,
    variants: Vec<String>,
    #[serde(default)]
    implement_traits: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct MessageFieldsSpec {
    fields: HashMap<String, FieldSpec>,
}

#[derive(Debug, Serialize, Deserialize)]
struct MessageSpec {
    #[serde(rename = "name")]
    original_name: String,
    #[serde(skip, default)]
    generated_name: String, // Will store the auto-numbered name
    description: String,
    request: MessageFieldsSpec,
    response: MessageFieldsSpec,
}

#[derive(Debug, Serialize, Deserialize)]
struct MessageCategory {
    category: String,
    messages: Vec<MessageSpec>,
}

#[derive(Debug, Serialize, Deserialize)]
struct MessageDefinition {
    settings: Settings,
    common_structs: HashMap<String, StructSpec>,
    enums: HashMap<String, EnumSpec>,
    error_message: StructSpec,
    messages: Vec<MessageCategory>,
}
fn assign_message_numbers(
    spec: &mut MessageDefinition, 
    prefix: &str,
    start_number: u32,
    num_digits: u8,
    enable_prefix: bool
) {
    let mut current_number = start_number;
    
    for category in &mut spec.messages {
        for message in &mut category.messages {
            if enable_prefix {
                // Format the number with leading zeros according to num_digits
                let number_str = match num_digits {
                    1 => format!("{}", current_number),
                    2 => format!("{:02}", current_number),
                    3 => format!("{:03}", current_number),
                    4 => format!("{:04}", current_number),
                    5 => format!("{:05}", current_number),
                    6 => format!("{:06}", current_number),
                    _ => format!("{:0width$}", current_number, width = num_digits as usize),
                };
                
                // Create the new message name: PREFIX + NUMBER + _ + ORIGINAL_NAME
                message.generated_name = format!("{}{}_{}",
                    prefix, number_str, message.original_name);
            } else {
                // Just use the original name without prefixing
                message.generated_name = message.original_name.clone();
            }

            debug!("Assigning message name: {}", message.generated_name);
            current_number += 1;
        }
    }
}

fn generate_rust_code(spec: &MessageDefinition) -> String {
    let mut code = String::new();

    // File header
    code.push_str("// This file was automatically generated. DO NOT EDIT MANUALLY!\n");
    code.push_str("// Generated by genrmsg - MC Project Effort Message Generator\n\n");
    
    // Module documentation
    code.push_str(&format!("//! {}\n\n", spec.settings.module_doc));
    
    // Allow camel case for message names
    code.push_str("#![allow(non_camel_case_types)]\n\n");

    // Standard imports
    code.push_str("use chrono::{DateTime, NaiveDate, Utc};\n");
    code.push_str("use serde::{Deserialize, Serialize};\n");
    code.push_str("use std::fmt::{self, Display};\n");
    code.push_str("use std::str::FromStr;\n\n");

    // Generate enums
    for (enum_name, enum_spec) in &spec.enums {
        code.push_str(&format!("/// {}\n", enum_spec.description));
        code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n");
        code.push_str(&format!("pub enum {} {{\n", enum_name));
        
        for variant in &enum_spec.variants {
            code.push_str(&format!("    {},\n", variant));
        }
        
        code.push_str("}\n\n");

        // Implement traits
        if enum_spec.implement_traits.contains(&"Display".to_string()) {
            code.push_str(&format!("impl Display for {} {{\n", enum_name));
            code.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
            code.push_str("        match self {\n");
            
            for variant in &enum_spec.variants {
                code.push_str(&format!("            {}::{} => write!(f, \"{}\"),\n", 
                    enum_name, variant, variant.to_lowercase()));
            }
            
            code.push_str("        }\n");
            code.push_str("    }\n");
            code.push_str("}\n\n");
        }

        if enum_spec.implement_traits.contains(&"FromStr".to_string()) {
            code.push_str(&format!("impl FromStr for {} {{\n", enum_name));
            code.push_str("    type Err = &'static str;\n\n");
            code.push_str("    fn from_str(s: &str) -> Result<Self, Self::Err> {\n");
            code.push_str("        match s {\n");
            
            for variant in &enum_spec.variants {
                code.push_str(&format!("            \"{}\" => Ok({}::{}),\n", 
                    variant.to_lowercase(), enum_name, variant));
            }
            
            code.push_str("            _ => Err(\"Invalid format\"),\n");
            code.push_str("        }\n");
            code.push_str("    }\n");
            code.push_str("}\n\n");
        }
    }

    // Generate common structs
    for (struct_name, struct_spec) in &spec.common_structs {
        code.push_str(&format!("/// {}\n", struct_spec.description));
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str(&format!("pub struct {} {{\n", struct_name));
        
        for (field_name, field) in &struct_spec.fields {
            code.push_str(&format!("    /// {}\n", field.description));
            code.push_str(&format!("    pub {}: {},\n", field_name, field.type_name));
        }
        
        code.push_str("}\n\n");
    }

    // Generate error message
    code.push_str("/// Error message for all possible errors\n");
    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str("pub struct M900_Error {\n");
    
    for (field_name, field) in &spec.error_message.fields {
        code.push_str(&format!("    /// {}\n", field.description));
        code.push_str(&format!("    pub {}: {},\n", field_name, field.type_name));
    }
    
    code.push_str("}\n\n");

    // Implement Display for error message
    code.push_str("impl Display for M900_Error {\n");
    code.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    code.push_str("        write!(f, \"Error {}: {}\", self.error_id, self.error_message)\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate message structs
    let mut message_enum_variants = Vec::new();

    for category in &spec.messages {
        code.push_str(&format!("// {} messages\n", category.category));
        
        for message in &category.messages {
            let request_name = &message.generated_name;
            let response_name = format!("{}_Reply", request_name);
                     
            // Request struct
            code.push_str(&format!("/// {} - Request\n", message.description));
            code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
            code.push_str(&format!("pub struct {} {{\n", request_name));
            
            for (field_name, field) in &message.request.fields {
                code.push_str(&format!("    /// {}\n", field.description));
                code.push_str(&format!("    pub {}: {},\n", field_name, field.type_name));
            }
            
            code.push_str("}\n\n");

            // Response struct
            code.push_str(&format!("/// {} - Response\n", message.description));
            code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
            code.push_str(&format!("pub struct {} {{\n", response_name));
            
            for (field_name, field) in &message.response.fields {
                code.push_str(&format!("    /// {}\n", field.description));
                code.push_str(&format!("    pub {}: {},\n", field_name, field.type_name));
            }
            
            code.push_str("}\n\n");

            // Add to enum variants
            message_enum_variants.push((request_name.clone(), response_name));
        }
        
        code.push_str("\n");
    }

    // Generate Message enum
    code.push_str("/// A wrapper enum for all message types\n");
    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str("pub enum Message {\n");
    
    // Message variants
    for (request, response) in &message_enum_variants {
        code.push_str(&format!("    {}({}),\n", request, request));
        code.push_str(&format!("    {}({}),\n", response, response));
    }
    
    // Add error message
    code.push_str("    M900_Error(M900_Error),\n");
    code.push_str("}\n\n");

    // Implement Display for Message enum
    code.push_str("impl Display for Message {\n");
    code.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    code.push_str("        match self {\n");
    
    for (request, response) in &message_enum_variants {
        code.push_str(&format!("            Message::{}(_) => write!(f, \"{}\"),\n", 
            request, request));
        code.push_str(&format!("            Message::{}(_) => write!(f, \"{}\"),\n", 
            response, response));
    }
    
    code.push_str("            Message::M900_Error(_) => write!(f, \"M900_Error\"),\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Helper functions for serialization
    code.push_str("// Helper functions for message serialization and deserialization\n");
    code.push_str("pub fn serialize_message(msg: &Message) -> Result<Vec<u8>, bincode::Error> {\n");
    code.push_str("    bincode::serialize(msg)\n");
    code.push_str("}\n\n");
    
    code.push_str("pub fn deserialize_message(bytes: &[u8]) -> Result<Message, bincode::Error> {\n");
    code.push_str("    bincode::deserialize(bytes)\n");
    code.push_str("}\n");

    code
}

#[derive(Parser)]
#[clap(
    name = "genrmsg",
    about = "Generate Rust message code from YAML specification",
    author = "Johan Persson <johan162@gmail.com>",
    version = "1.0"
)]
struct Cli {
    /// Sets the input YAML file
    #[clap(short = 'i', long = "input", value_name = "FILE", required = true)]
    input: String,
    
    /// Sets the output Rust file (overrides the one in YAML if specified)
    #[clap(short = 'o', long = "output", value_name = "FILE")]
    output: Option<String>,
    
    /// Sets the message prefix (defaults to "M")
    #[clap(short = 'p', long = "prefix", value_name = "PREFIX", default_value = "M")]
    prefix: String,
    
    /// Starting number for message numbering (defaults to 1)
    #[clap(short = 's', long = "start", value_name = "NUMBER", default_value = "1")]
    start_number: u32,
    
    /// Number of digits to use for the message number (defaults to 3)
    #[clap(short = 'd', long = "digits", value_name = "DIGITS", default_value = "3")]
    num_digits: u8,

    /// Enable prefixing of message names (enabled by default)
    #[clap(short = 'm', long = "prefix-messages", action = clap::ArgAction::Set, default_value = "true")]
    prefix_messages: bool,

    /// Sets the verbosity level, 0=Error, 1=Warn, 2=Info, 3=Debug, 4=Trace (default is 0)
    #[clap(short = 'v', long = "verbose", value_name = "LEVEL", default_value = "0")]
    verbose: u8,

}



fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

     // Initialize logging based on verbosity
    let log_level = match cli.verbose {
        0 => log::LevelFilter::Error,
        1 => log::LevelFilter::Warn,
        2 => log::LevelFilter::Info,
        3 => log::LevelFilter::Debug,
        _ => log::LevelFilter::Trace,
    };
    
    env_logger::Builder::new()
        .filter_level(log_level)
        .init();
    
    info!("Reading message specification from: \"{}\"", cli.input);
    
    let input_file = &cli.input;

    // Read the YAML file
    let yaml_content = fs::read_to_string(input_file)?;
    
    // Parse the YAML specification
    let mut spec: MessageDefinition = serde_yaml::from_str(&yaml_content)?;
    
   // Assign message numbers, respecting the prefix_messages flag
    assign_message_numbers(
        &mut spec, 
        &cli.prefix, 
        cli.start_number, 
        cli.num_digits,
        cli.prefix_messages
    );

    // Generate Rust code
    let output_file = cli.output
        .unwrap_or_else(|| spec.settings.output_file.clone());
    let rust_code = generate_rust_code(&spec);
    
    // Create parent directories if they don't exist
    if let Some(parent) = Path::new(&output_file).parent() {
        fs::create_dir_all(parent)?;
    }
    
    // Write the output file
    fs::write(&output_file, rust_code)?;
    
    info!("Successfully generated message code to: \"{}\"", output_file);
    
    Ok(())
}
